gui:
  showFileTree: false
  showListFooter: false
  showRandomTip: false
  showBottomLine: false
  showCommandLog: false
notARepository: 'quit'
os:
  edit: 'hx {{filename}}'
  editAtLine: 'hx {{filename}}:{{line}}'
